### ISSUE TITLE
Users graphic disappear in admin dashboard

### ISSUE THREAD

**Issue by ctlui** [lianglee/fancybox#2]
HI,
When FancyBox 1.4 is enabled the users graphics (1st one) disappear on admin dashbord.
Get this js error:
TypeError: $(...).fancybox is not a function
in https://rxxx.domain.tld/js/view/opensource.socialnetwork.js

Ossn.RegisterStartupFunction(function(){
  $(document).ready(function(){  
        $(".activity-item-container .description img").fancybox({

Thanks - Eric

**Comment by lianglee** [comment]
Thanks Eric for report, i'll fix this issue soon, we just need to load fancybox function on frontend only , the reason it disappear is there is no fancybox lib loaded in backend

**Comment by lianglee** [comment]
Fixed
